### ISSUE TITLE
[Feature 12] Choose Features

### ISSUE THREAD

**Issue by Ford-Robert** [CSC207-2023Y-UofT/ai-playground#13]
Responsible for implementing user story 4 (creating the requisite controllers and presenters). Modifies the input data based on the 3 transformations that can be applied to either the x_1 and x_2 data points.

**Comment by Rishit-dagli** [comment]
So, what do you think of adding just more points to the dataset, for example points right now are x,y and if you choose squared you add a points x^2,y

**Comment by Ford-Robert** [comment]
That is an excellent idea! I have another question for how to arrange the data for training. As it stands the output after applying the necessary features is the following (example: where only Y^2 feature is chosen);

[
    [   // Original Dataset 1 (BLUE POINTS)
        [x11, x12, x13, ...],  // x values
        [y11, y12, y13, ...]   // y values

    ],
    [   // Original Dataset 2 (ORANGE POINTS)
        [x21, x22, x23, ...],  // x values
        [y21, y22, y23, ...]   // y values
    ],
    ...
    [   // Squared Dataset 1 (BLUE POINTS)
        [x11, x12, x13, ...],              // same x values
        [y11*y11, y12*y12, y13*y13, ...]   // squared y values
    ],
    [   // Squared Dataset 2 (ORANGE POINTS)
        [x21, x22, x23, ...],              // same x values
        [y21*y21, y22*y22, y23*y23, ...]   // squared y values
    ]]


I could also arrange it in a IND Array as we spoke about yesterday. As this would be better suited for the Training Entity. Could write out an example of what that array would look like because I dont fully understand how it would be arranged.
