### ISSUE TITLE
Transform Dataset into INDArray Pairs of Iterables

### ISSUE THREAD

**Issue by Rishit-dagli** [CSC207-2023Y-UofT/ai-playground#36]
Currently, we have a dataset as an `ArrayList` which we need to transform to a `List<Pair<INDArray, INDArray>>` for the modeling, I particularly chose this to accommodate other features we later have.

The way we create this is:

- create $x$: an array of size 2 (or more if there are other features) containing $(x_1,x_2)$ (or lets say $(x_1,x_2,x_1x_2, x_2^2)$ if there are other features)
- create $y$: create an array of size 1 for the label, that is 1 or 0
- Convert $x$ and $y$ to `INDArray` and create a `Pair` with both
- Do this multiple times for the dataset and create a `List` of such pairs

I also have an example which I was testing with where the dataset is just the "and" operator dataset.

```java
// Example on the kind of data we need, example for a simple "and" operation dataset, we want
// the same, two or more numbers for the features and 1 number (1 or 0) for label.

   public static Pair<INDArray, INDArray> buildDataset(final boolean bitA, final boolean bitB) {
     final double[] input = new double[2];
     final double[] labels = new double[1];

//  Just some code to compute the labels
     for (int idx = 0; idx < labels.length; ++idx) {
       final boolean result = bitA && bitB;
       input[idx * 2]     = bitA   ? 1.0 : 0.0;
       input[idx * 2 + 1] = bitB   ? 1.0 : 0.0;
       labels[idx]        = result ? 1.0 : 0.0;
     }


     return Pair.create(
             Nd4j.create(input),
             Nd4j.create(labels)
     );
   }

    public List<Pair<INDArray, INDArray>> buildData() {
        final ArrayList<Pair<INDArray, INDArray>> result = new ArrayList<>(4);

        for (final boolean bitA : new boolean[]{true, false}) {
            for (final boolean bitB : new boolean[]{true, false}) {
                result.add(buildData(bitA, bitB));
            }
        }

        return result;
    }
```

/area datasets

**Comment by Shivesh777** [comment]
I can take this up, please merge PR #27 before I can start working on this.
