### ISSUE TITLE
[Feature 9] Documentation

### ISSUE THREAD

**Issue by Shivesh777** [CSC207-2023Y-UofT/ai-playground#8]
Write informative and self-explanatory documentation for the required files in the project.

**Comment by Rishit-dagli** [comment]
About this, we probably want to build the documentation using GitHub Actions and then push documentation-generated static files to a branch on this repo and then host that branch on GitHub Pages. I don't know if its helpful but I do have Python examples with Sphinx on doing this workflow at https://github.com/Rishit-dagli/TF-Watcher (checkout `docs/` and `.github/workflows/`) and the result is https://rishit-dagli.github.io/TF-Watcher/ which is automatically updated on each change to the repo (and also generates a LaTeX PDF for the documentation and attaches it to a release, but we can skip this if we want). 

Let me know if you need any help with CI/CD or the DevOps-like stuff here.

/kind documentation

**Comment by Rishit-dagli** [comment]
About this, we probably want to build the documentation using GitHub Actions and then push documentation-generated static files to a branch on this repo and then host that branch on GitHub Pages. I don't know if its helpful but I do have Python examples with Sphinx on doing this workflow at https://github.com/Rishit-dagli/TF-Watcher (checkout `docs/` and `.github/workflows/`) and the result is https://rishit-dagli.github.io/TF-Watcher/ which is automatically updated on each change to the repo (and also generates a LaTeX PDF for the documentation and attaches it to a release, but we can skip this if we want). 

Let me know if you need any help with CI/CD or the DevOps-like stuff here.

/kind documentation

**Comment by Rishit-dagli** [comment]
About this, we probably want to build the documentation using GitHub Actions and then push documentation-generated static files to a branch on this repo and then host that branch on GitHub Pages. I don't know if its helpful but I do have Python examples with Sphinx on doing this workflow at https://github.com/Rishit-dagli/TF-Watcher (check out `docs/` and `.github/workflows/`) and the result is https://rishit-dagli.github.io/TF-Watcher/ which is automatically updated on each change to the repo (and also generates a LaTeX PDF for the documentation and attaches it to a release, but we can skip this if we want). 

Let me know if you need any help with CI/CD or the DevOps-like stuff here.

/kind documentation
